var jetty = require('./jettyThreads.js');
var jettyPerServer = require('./jetty_perserver.js');
var desktopOrders = require('./desktopOrders.js');
var transactionsDrop = require('./transactions_drop.js');
var transactionsDrop_woking = require('./transaction_drop_woking.js');
var transactionsDrop_jubilee = require('./transaction_drop_jubilee.js');
var productSearchApi = require('./productSearchApi.js');
var getProductsBySku = require('./getProductsBySku.js');
var getProductsInCategory = require('./getProductsInCategory.js');
var getBasket = require('./getBasket.js');
var avgResponseTime = require('./avgResponseTime.js');
var diffAvgResponseTime = require('./diffAvgResponseTime.js');
var pageDrop = require('./pageDrop.js');
var getProducts = require('./getProducts.js');

//now call all
jetty();
jettyPerServer();
desktopOrders();
transactionsDrop();
transactionsDrop_woking();
transactionsDrop_jubilee();
productSearchApi();
getProductsBySku();
getProductsInCategory();
getBasket();
avgResponseTime();
diffAvgResponseTime();
pageDrop();
getProducts();